#!/bin/bash
figlet ReDox
echo -e "                           By"
echo -e "                                 H4x0r Abub4kk3r\n"
echo "Automated Websites Reconnaissance and Doxing for Penetration Testing"
echo "No System Is Safe"
echo "--------------------------------------------------------"
#Checking for necessary tools

if ! command -v nmap > /dev/null; then
    echo "Error: nmap is not installed"
    exit 1
fi
if ! command -v gobuster > /dev/null; then
    echo "Error: gobuster is not installed"
    exit 1
fi
if ! command -v whatweb > /dev/null; then
    echo "Error: whatweb is not installed"
    exit 1
fi
if ! command -v jq > /dev/null; then
    echo "Error: jq is not installed"
    exit 1
fi

if [[ "$#" -ne 1 ]] || ! [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Usage: $0 IP_ADDRESS"
    exit 1
fi

read -p "Enter number of decoy IPs: " num_decoys

if [ $num_decoys -lt 2 ]; then
    echo "Enter at least 2 decoy IPs."
    exit 1
fi

for ((i=1; i<=$num_decoys; i++)); do
    read -p "Enter decoy IP $i: " decoy_ip
    decoy_list+="$decoy_ip,"
done

decoys=${decoy_list%?}
printf "\n -_-_-_-_-_-_-_-_-_ NMAP -_-_-_-_-_-_-_-_-_ \n\n" > results

echo "Running Nmap..."
nmap -T5 -F --open -n -Pn --min-rate=50 $1 -D $decoys -data-length 20 --scan-delay 2s | grep "^[0-9]*\/.*open.*" >>results
#With specific Ports like -p 21-25,80-85,139,8080 or By name -p ftp,udp,tcp,http,https

while read line
do
        if [[ $line == *open* ]] && [[ $line == *http* ]]
        then
        echo "Running Gobuster..."
        gobuster dir -u $1 -w /usr/share/wordlists/dirb/common.txt -qz > temp1
#use -d if_you_want more results with backup files and --wildcard  Force continued operation when wildcard found  (time consuming)

        echo "Running WhatWeb..."
        whatweb $1 -v > temp2

#Now testing for CVE related bugs
	echo "Now Testing For CVE Bugs"
        shodan host $1 > temp3

	fi
done < results

if [ -e temp1 ]
then
        printf "\n -_-_-_-_-_-_-_-_-_  DIRS -_-_-_-_-_-_-_-_-_ \n\n" >> results
        cat temp1 >> results
        rm temp1
fi

if [ -e temp2 ]
then
    printf "\n -_-_-_-_-_-_-_-_-_  WhatWeb -_-_-_-_-_-_-_-_-_ \n\n" >> results
        cat temp2 >> results
        rm temp2
fi

if [ -e temp3 ]
then
	printf "\n -_-_-_-_-_-_-_-_-_ CVE BUGS -_-_-_-_-_-_-_-_-_  \n\n" >> results
	cat temp3 >> results
	rm temp3
fi

cat results

echo -e "\n--------------------------------------------------------"
echo "*************** Now Doxing Ip Address ******************"
echo "--------------------------------------------------------"
res=$(curl http://ip-api.com/json/$1 -s)
status=$(echo $res | jq '.status' -r)
if [[ $status == "success" ]] 
then 
	city=$(echo $res | jq '.city' -r)
echo "CITY:" $city >> results
region=$(echo $res | jq '.regionName' -r)
echo "REGION:" $region
zip=$(echo $res | jq '.zip' -r)
echo "ZIP CODE:" $zip
lat=$(echo $res | jq '.lat' -r)
echo "LATITUDE:" $lat
lon=$(echo $res | jq '.lon' -r)
echo "LONGITUDE:"  $lon
timezone=$(echo $res | jq '.timezone' -r)
echo "TIMEZONE:" $timezone
isp=$(echo $res | jq '.isp' -r)
echo "ISP:" $isp
org=$(echo $res | jq '.org' -r)
echo "ORGANIZATION:" $org
as=$(echo $res | jq '.as' -r)
echo "AS:" $as
query=$(echo $res | jq '.query' -r)
echo "QUERY:" $query


#Do not copy my code(201-002-211)
#if you face any problem with jq install it : apt-get install jq -y

printf "\n\nTesting Done!! For $1 \n\n"

fi

